GET http://localhost:3000/

###
GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4NzY1MDZ9.bhqJTOkBCzfX-JMoE2YU4Qu4SnYL9oP7wa7bcaB741F6NinwrKeVn89-jcETNleU4Wx9nLmjGzc7J0AQKbtJ55AexybaMeCEAso5GcUgLquBe17fPDwMsPZWTFxPODKk4QRtn3pzeUQzDWww78DPY70rWvUqdBdQJnzkT46PStrl9imI6rGKHBkF9LtrN3zy_fqaakvu4qtYWtaFlymddShZezSgDOabRtiGc6nHUaD2QZnGraVqNNRSTVVefzltEBnEk-dB6_yUPR6j50Nrg8qudH3vs92egNylPCMQxsUEIYwZF-s-a22ySRCGMxlhvLTQU6MwBgWdcyrYToiyFHo_jwdx0WOBAbRkF1sHDA4jxbKh_NiXbUvyyXTl8is7mJGhc3KFrxvq7ryxPnzAe9Td6mFWxe7OYO5DV70_Z1c8qsWnHLCUdgYRHHIRwbWKPakWrh9TR3iC3aZQmRBb64GvhEWpmeb3CzfARXG5aWaYqxQehcqCtRmg_ZGNi5JBfhWsNfQVPaNmhu9eRTuseEdTxcFxopF6FEev1KziaWo3uQRsDcZv5INfyvyYMXEK7DThzu8OCWQ0-IebIKqaBewsXdGKLbB04QVgzJLi8M29JH9p5cKEbViRUhXOlBnCwx9D70vRIH9WntcHAdotO6rTdkgTPPrQ7mKPr3WMMOg